### ISSUE TITLE
Bug lors de la suppression d'un produit

### ISSUE THREAD

**Issue by jacquelotjeff** [jacquelotjeff/ShoppingList#26]
Je viens de remarquer que lorsqu'on supprime un produit de la liste de courses au clic sur la corbeille, on aperçoit très brièvement l'écran d'édition du produit.

https://github.com/jacquelotjeff/ShoppingList/blob/master/app/src/main/java/com/clevermind/shoppinglist/fragments/ShoppingListShowFragment.java#L134

Je pense qu'il faut rajouter pour chaque cas le return super.onOptionsItemSelected(item); :

```java
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.action_delete:
                deleteList(shoppingList);
                return super.onOptionsItemSelected(item);
            case R.id.action_edit:
                onClickEditListButton(shoppingList);
                return super.onOptionsItemSelected(item);
            case R.id.action_add:
                onClickAddProductButton(shoppingList);
                return super.onOptionsItemSelected(item);
            default:
                return super.onOptionsItemSelected(item);
        }
    }

```

**Comment by aturcey** [comment]
Je vois ça !

**Comment by jacquelotjeff** [comment]
J'avais oublié les break ... Mea Culpa , merci Adrien pour le correctif ;)
