### ISSUE TITLE
En tant qu'utilisateur je peux voir ma liste de mes courses

### ISSUE THREAD

**Issue by jacquelotjeff** [jacquelotjeff/ShoppingList#3]
- [x] Créer un écran affichant la liste de ses "listes de courses"

Url à requêter pour récupérer la liste de ses produits : 
**GET** : http://appspaces.fr/esgi/shopping_list/shopping_list/list.php

A envoyer dans le flux : 
- [x] token de l'utilisateur connecté (string)

En retour : 
- Code (ResultCode)
- result (List<ShoppingList>)

- [x] Gérer les exceptions de retours : Message montrant qu'il n'existe pas encore de shopping List.
- [x] Gérer le succès, afficher la liste des produits de la shopping list.

Informations utiles : Liste des codes pouvant être retourné par l'API (ResultCode)
<img width="418" alt="capture d ecran 2016-11-15 a 20 06 24" src="https://cloud.githubusercontent.com/assets/11046841/20319607/1d8401f0-ab6f-11e6-8559-3efafe17bfac.png">

**Comment by jacquelotjeff** [comment]
@aturcey Mettre un message pour que l'utilisateur sache qu'il n'a pas encore créé de liste de courses.

**Comment by aturcey** [comment]
Template a finaliser

**Comment by jacquelotjeff** [comment]
@aturcey Template déplacé dans une autre issue
