### ISSUE TITLE
En tant qu'utilisateur je peux voir les détails d'une liste de courses

### ISSUE THREAD

**Issue by jacquelotjeff** [jacquelotjeff/ShoppingList#7]
Faire une vue représentant les détails de ma liste de courses (accessible au clic sur la liste de courses) : 

- [x] Faire apparaitre le titre de la liste de courses
- [x] Afficher dans une listView la liste des produits liées à la liste de courses 

Url à requêter pour récupérer la liste des produits de ma liste de courses : 
**GET** : http://appspaces.fr/esgi/shopping_list/product/list.php

Il faut passer en paramètre : 
- [x] token de l'utilisateur connecté (string)
- [x] shopping_list_id (string) : id de la liste de courses

En retour : 
- Code (ResultCode) => Le code réponse du service
- result (List<Product>) => La liste de produits de la liste de courses)

- [x] Gérer les exceptions de retours : Message montrant que la liste des produits est vide
- [x] Gérer le succès, afficher la liste des produits de la liste de courses

Informations utiles : Liste des codes pouvant être retourné par l'API (ResultCode)
<img width="418" alt="capture d ecran 2016-11-15 a 20 06 24" src="https://cloud.githubusercontent.com/assets/11046841/20319607/1d8401f0-ab6f-11e6-8559-3efafe17bfac.png">

**Comment by aturcey** [comment]
template a finaliser

**Comment by jacquelotjeff** [comment]
@aturcey Pour le template : Faire le même rendu que pour la liste de courses ;)

**Comment by jacquelotjeff** [comment]
Invalid, so => close.
