### ISSUE TITLE
En tant qu'utilisateur, je peux éditer un produit de ma liste de courses

### ISSUE THREAD

**Issue by jacquelotjeff** [jacquelotjeff/ShoppingList#9]
- [ ] Dans la vue de détails d'une liste de courses , dans la listView des produits, sur chaque item de produits, créer un bouton permettant d'éditer le produit

- [ ] Créer la vue et le formulaire permettant d'éditer le produit

Champs à inclure dans le formulaire  : 
- [ ] name (string) : nom du produit
- [ ] quantity (string) : quantité (optionnel) 
- [ ] price (double) : Prix du produit (optionnel) 

Url à requêter pour éditer un produit d'une liste de produits : 
**GET** : http://appspaces.fr/esgi/shopping_list/product/edit.php

Il faut passer en paramètre : 
- [ ] token de l'utilisateur connecté (string)
- [ ] name : nom du produit
- [ ] quantity : quantité ajoutée (non obligatoire)
- [ ] price : prix du produit (non obligatoire

En retour : 
- Code (ResultCode) => Code de réponse du service
- result (int => 0 : error, 1 : succès)

- [ ] Gérer les exceptions de retours : Message montrant que le produit n'a pas pu s'éditer.
- [ ] Gérer le succès, afficher un message de succès 

Informations utiles : Liste des codes pouvant être retourné par l'API (ResultCode)
<img width="418" alt="capture d ecran 2016-11-15 a 20 06 24" src="https://cloud.githubusercontent.com/assets/11046841/20319607/1d8401f0-ab6f-11e6-8559-3efafe17bfac.png">

**Comment by aturcey** [comment]
Fait
